#!/bin/bash
#SBATCH --job-name=garbage_classification
#SBATCH --output=outputtc.txt
#SBATCH --error=errortc.txt
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16GB
#SBATCH --time=04:00:00



# Activate the virtual environment
source ~/software/init-conda
conda activate pytorch

# Change to the working directory
python /work/TALC/enel645_2025w/transfer_learning/a2ip/tc1.py
# Run the training script
conda deactivate
