#!/bin/bash
#SBATCH --job-name=garbage_classification
#SBATCH --output=outputic.text
#SBATCH --error=erroric.text
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=2
#SBATCH --mem=16GB
#SBATCH --time=06:00:00



# Activate the virtual environment
source ~/software/init-conda
conda activate pytorch

# Change to the working directory
python /work/TALC/enel645_2025w/transfer_learning/a2ip/ic1.py
# Run the training script
conda deactivate
